version: '3'

services:
  reviews:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  database:
    image: mysql:5.7
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: udemy
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports: 
      - '3306:3306'
    expose:
      - 3306
